# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8405cd1935f5576cb432550461463f7d17a986af7d39418d4600add24eaf012bd5205ebc163d32dedec7e4bbe837d70e21b05ccdb5ee5959ca25da032d41bd33

test:
  secret_key_base: b5d61c6c77cd90aafad2b38516a60a2feca863d467bbd94bf9feb122f837e4085eae1e552d5ec8d5fec32aab68493fbeaaee849d43cffe75486e7543bde94970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
